/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { UserTestService } from "../userTest.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { UserTestCreateInput } from "./UserTestCreateInput";
import { UserTest } from "./UserTest";
import { UserTestFindManyArgs } from "./UserTestFindManyArgs";
import { UserTestWhereUniqueInput } from "./UserTestWhereUniqueInput";
import { UserTestUpdateInput } from "./UserTestUpdateInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class UserTestControllerBase {
  constructor(
    protected readonly service: UserTestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: UserTest })
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createUserTest(
    @common.Body() data: UserTestCreateInput
  ): Promise<UserTest> {
    return await this.service.createUserTest({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,

        test: data.test
          ? {
              connect: data.test,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,

        user: {
          select: {
            id: true,
          },
        },

        test: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [UserTest] })
  @ApiNestedQuery(UserTestFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userTests(@common.Req() request: Request): Promise<UserTest[]> {
    const args = plainToClass(UserTestFindManyArgs, request.query);
    return this.service.userTests({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,

        user: {
          select: {
            id: true,
          },
        },

        test: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: UserTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async userTest(
    @common.Param() params: UserTestWhereUniqueInput
  ): Promise<UserTest | null> {
    const result = await this.service.userTest({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        score: true,

        user: {
          select: {
            id: true,
          },
        },

        test: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: UserTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateUserTest(
    @common.Param() params: UserTestWhereUniqueInput,
    @common.Body() data: UserTestUpdateInput
  ): Promise<UserTest | null> {
    try {
      return await this.service.updateUserTest({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,

          test: data.test
            ? {
                connect: data.test,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          score: true,

          user: {
            select: {
              id: true,
            },
          },

          test: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: UserTest })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteUserTest(
    @common.Param() params: UserTestWhereUniqueInput
  ): Promise<UserTest | null> {
    try {
      return await this.service.deleteUserTest({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          score: true,

          user: {
            select: {
              id: true,
            },
          },

          test: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }
}
