/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import * as nestAccessControl from "nest-access-control";
import * as gqlACGuard from "../../auth/gqlAC.guard";
import { GqlDefaultAuthGuard } from "../../auth/gqlDefaultAuth.guard";
import * as common from "@nestjs/common";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { UserTest } from "./UserTest";
import { UserTestCountArgs } from "./UserTestCountArgs";
import { UserTestFindManyArgs } from "./UserTestFindManyArgs";
import { UserTestFindUniqueArgs } from "./UserTestFindUniqueArgs";
import { CreateUserTestArgs } from "./CreateUserTestArgs";
import { UpdateUserTestArgs } from "./UpdateUserTestArgs";
import { DeleteUserTestArgs } from "./DeleteUserTestArgs";
import { User } from "../../user/base/User";
import { Test } from "../../test/base/Test";
import { UserTestService } from "../userTest.service";
@common.UseGuards(GqlDefaultAuthGuard, gqlACGuard.GqlACGuard)
@graphql.Resolver(() => UserTest)
export class UserTestResolverBase {
  constructor(
    protected readonly service: UserTestService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}

  @graphql.Query(() => MetaQueryPayload)
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "read",
    possession: "any",
  })
  async _userTestsMeta(
    @graphql.Args() args: UserTestCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => [UserTest])
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "read",
    possession: "any",
  })
  async userTests(
    @graphql.Args() args: UserTestFindManyArgs
  ): Promise<UserTest[]> {
    return this.service.userTests(args);
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.Query(() => UserTest, { nullable: true })
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "read",
    possession: "own",
  })
  async userTest(
    @graphql.Args() args: UserTestFindUniqueArgs
  ): Promise<UserTest | null> {
    const result = await this.service.userTest(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserTest)
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "create",
    possession: "any",
  })
  async createUserTest(
    @graphql.Args() args: CreateUserTestArgs
  ): Promise<UserTest> {
    return await this.service.createUserTest({
      ...args,
      data: {
        ...args.data,

        user: args.data.user
          ? {
              connect: args.data.user,
            }
          : undefined,

        test: args.data.test
          ? {
              connect: args.data.test,
            }
          : undefined,
      },
    });
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @graphql.Mutation(() => UserTest)
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "update",
    possession: "any",
  })
  async updateUserTest(
    @graphql.Args() args: UpdateUserTestArgs
  ): Promise<UserTest | null> {
    try {
      return await this.service.updateUserTest({
        ...args,
        data: {
          ...args.data,

          user: args.data.user
            ? {
                connect: args.data.user,
              }
            : undefined,

          test: args.data.test
            ? {
                connect: args.data.test,
              }
            : undefined,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @graphql.Mutation(() => UserTest)
  @nestAccessControl.UseRoles({
    resource: "UserTest",
    action: "delete",
    possession: "any",
  })
  async deleteUserTest(
    @graphql.Args() args: DeleteUserTestArgs
  ): Promise<UserTest | null> {
    try {
      return await this.service.deleteUserTest(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => User, {
    nullable: true,
    name: "user",
  })
  @nestAccessControl.UseRoles({
    resource: "User",
    action: "read",
    possession: "any",
  })
  async getUser(@graphql.Parent() parent: UserTest): Promise<User | null> {
    const result = await this.service.getUser(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @graphql.ResolveField(() => Test, {
    nullable: true,
    name: "test",
  })
  @nestAccessControl.UseRoles({
    resource: "Test",
    action: "read",
    possession: "any",
  })
  async getTest(@graphql.Parent() parent: UserTest): Promise<Test | null> {
    const result = await this.service.getTest(parent.id);

    if (!result) {
      return null;
    }
    return result;
  }
}
